title: Nguyen Thi Huyen My
#logo: /assets/img/avt.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
social_links:
  - name: LinkedIn
    url: "https://www.linkedin.com/in/huyen-my-a90816235"
    icon: "fab fa-linkedin"
  - name: GitHub
    url: "https://github.com/huyenmy239"
    icon: "fab fa-github"
